name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Adding Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - name: Prepare and deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install
          npm run ng -- deploy --base-href=/webgpu-app/ --name="Michael Liang" --email=mliang1987@gmail.com
